// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQpeHhfEWEPgHFN84nI1CPPgxn56p6qQ',
    appId: '1:201503699171:web:fc34f7e81ad857f16155d6',
    messagingSenderId: '201503699171',
    projectId: 'mynotes-96576',
    authDomain: 'mynotes-96576.firebaseapp.com',
    storageBucket: 'mynotes-96576.appspot.com',
    measurementId: 'G-6NFP2M39NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAD2LoO6WgDl7zijr_HN2W38aJbGgQb1U',
    appId: '1:201503699171:android:a34c20e6dd657d036155d6',
    messagingSenderId: '201503699171',
    projectId: 'mynotes-96576',
    storageBucket: 'mynotes-96576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCp7pdBstUkrG0MNxnV6qzDz--eSPOn4',
    appId: '1:201503699171:ios:c313e30ac9f096396155d6',
    messagingSenderId: '201503699171',
    projectId: 'mynotes-96576',
    storageBucket: 'mynotes-96576.appspot.com',
    iosClientId:
        '201503699171-5i1gjce33lv30faqk02f5c4mh5cajmao.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvCp7pdBstUkrG0MNxnV6qzDz--eSPOn4',
    appId: '1:201503699171:ios:65af0df97c9753496155d6',
    messagingSenderId: '201503699171',
    projectId: 'mynotes-96576',
    storageBucket: 'mynotes-96576.appspot.com',
    iosClientId:
        '201503699171-kd86hkjotc6l7m2npdojum9r17ebrfh7.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mynotes.RunnerTests',
  );
}
